name: build-debian
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - name: Install dependencies
        run: |
          echo "deb-src http://deb.debian.org/debian trixie main" >> /etc/apt/sources.list
          apt update --yes
          apt upgrade --yes
          apt build-dep mpv-mpris --yes

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: debian-trixie
          path: mpris.so
          if-no-files-found: error
